services:
  - type: web
    name: radarjobs-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    envVars:
      - key: FRONTEND_URL
        value: https://frontend-peach-nine-51.vercel.app
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
